name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install prerequisites
      run: |
        pip install -r requirements.txt --upgrade

    - name: Run linter
      run: |
        flake8 view_coverage.py
        flake8 coverage_tools.py

    - name: Run tests
      run: |
        python -m pytest test
